### ISSUE TITLE
/api/v3/vulnerabilities/servers/{id} params Groups

### ISSUE THREAD

**Issue by simon6931** [Cyberwatch/cyberwatch_api#15]
the code  
update_server = Cyberwatch_Pyhelper().request(
                            method="put",
                            endpoint="/api/v3/vulnerabilities/servers/{id}",
                            params={'id': ID , 'description': "description", 'groups': [1] }
                            )
doesn't update the group but update description.

**Comment by hezanathos** [comment]
Thanks for reporting this.
We will include a fix it in the next release.

**Comment by TheoMauri** [comment]
Hello, 
For PUT and POST methods, you need to use **body_params** instead of **params** as follows:
`update_server = Cyberwatch_Pyhelper().request(
method="put",
endpoint="/api/v3/vulnerabilities/servers/{id}",
body_params={'id': ID , 'description': "description", 'groups': [1] }
)`
This information has been added in the documentation.

**Comment by simon6931** [comment]
Hello, 

I can update groups but I have an other issue link to it
--endpoint="/api/v3/vulnerabilities/servers/1"

Traceback (most recent call last):
  File "api/ajout_group_asset.py", line 136, in <module>
    update_server = Cyberwatch_Pyhelper().request(
  File "....env/lib/python3.8/site-packages/cyberwatch_api.py", line 50, in wrapper
    params_id = kwargs.get("params").get("id")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by hezanathos** [comment]
Hello,

Apologies for the delayed response.
Thanks again for your feedback! That's appreciated and helped us troubleshoot.
 This problem has been addressed and released. We now suggest to use only body_params and changed the code accordingly.

Regards,
