### ISSUE TITLE
cyberwatch-cli does not correctly handle file given as arguments with bash expansion

### ISSUE THREAD

**Issue by PierreHachard** [Cyberwatch/cyberwatch_api#55]
In the README, there is an example stating that we can use the command as follows:

```
cyberwatch-cli airgap upload-compliance /tmp/cyberwatch-airgap-compliance/uploads/*
```

In reality using cyberwatch-cli in such a way will only import the first file present in the `uploads` directory.

Say my directory containing the files I want to import is named `import_dir`, I have tried the following:

1. 
```
cyberwatch-cli airgap upload import_dir/*
```

2.
```
cd import_dir/
cyberwatch-cli airgap upload *
```

Both only import the first file in the directory.
I haven't tried with more complex bash expansion but I guess the behaviour will be the same

**Comment by tarraschk** [comment]
Je confirme le problème, je l'ai rencontré aujourd'hui :)
